server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false  # Deshabilitar Eureka
      routes:
        - id: ninja-service
          uri: http://ninja-service:8081  # Conexi√≥n DIRECTA al contenedor
          predicates:
            - Path=/api/ninjas/**
          filters:
            - RewritePath=/api/ninjas/(?<segment>.*), /ninjas/$\{segment}
